[tool.pdm]

[project]
name = "IRobotAPI"
version = "0.1"
description = ""
authors = [
    {name = "João Thallis", email = "joaothallis@icloud.com"},
]
dependencies = [
    "flask-restx>=1.1.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
